# Use the ECR-hosted Amazon Corretto image
FROM 509554853164.dkr.ecr.us-east-1.amazonaws.com/customermanagement:amazoncorretto-17

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file generated by your build tool
COPY target/customerManagement-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose the application’s port
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "/app/app.jar"]